'use strict';
const $ = id => document.getElementById(id);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state = null, filter = 'all', page = 1, selected = new Set(), preview = null, pending = false, toastTimer;
const labels = {PAYED:'결제완료',PAYMENT_WAITING:'결제대기',DELIVERING:'배송 중',DELIVERED:'배송완료',PURCHASE_DECIDED:'구매확정',CANCELED:'취소',RETURNED:'반품',EXCHANGED:'교환',CANCELED_BY_NOPAYMENT:'미결제 취소'};
const shippingLabels = {success:'반영 확인',accepted:'성공 응답 · 확인 대기',failed:'실패',unknown:'결과 미확인',sending:'송신 중'};
function dateText(v){if(!v)return '아직 수집 전';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('ko-KR',{timeZone:'Asia/Seoul',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});}
function toast(message,error=false){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').className='toast'+(error?' error':'');toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),6000);}
async function api(path,body,raw=false){const options={};if(body!==undefined){options.method='POST';options.headers={'x-csrf-token':state?.csrf || '', 'Content-Type':raw?'application/octet-stream':'application/json'};options.body=raw?body:JSON.stringify(body);}const response=await fetch(path,options);if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.error||`요청 실패 (${response.status})`);}return response;}
async function action(fn){if(pending)return;pending=true;renderBusy();try{await fn();}catch(error){toast(error.message,true);}finally{pending=false;await refresh().catch(()=>{});renderBusy();}}
function renderBusy(){const busy=pending||state?.busy;$('collect-top').disabled=!!busy;$('collect-top').textContent=busy?(state?.busy||'처리 중…'):'↻ 지금 주문 수집';$('send-open').disabled=!!busy||!preview?.valid||!state?.dispatch_enabled;$('send-confirm').disabled=!!busy;}
async function refresh(){state=await (await api('/api/state')).json();render();}
function attention(o){return !!o.claim||['failed','unknown','accepted'].includes(o.shipment?.state);}
function filtered(){const q=$('search').value.trim().toLowerCase();return state.orders.filter(o=>(filter==='all'||filter==='waiting'&&o.status==='PAYED'||filter==='shipped'&&['DELIVERING','DELIVERED','PURCHASE_DECIDED'].includes(o.status)||filter==='attention'&&attention(o))&&(!q||[o.id,o.order_id,o.name,o.recipient].some(v=>String(v).toLowerCase().includes(q))));}
function showView(view){document.querySelectorAll('.view').forEach(e=>e.classList.toggle('hidden',e.id!==view+'-view'));document.querySelectorAll('.nav[data-view]').forEach(e=>e.classList.toggle('active',e.dataset.view===view));const titles={orders:['주문 관리','주문 수집부터 발주서, 송장 송신까지 한곳에서 처리하세요.'],invoices:['송장 업로드·송신','엑셀에 입력한 송장번호를 검토하고 스마트스토어로 보내세요.'],history:['처리 내역','수집과 송신의 결과를 시간순으로 확인하세요.']};$('page-title').textContent=titles[view][0];$('breadcrumb').textContent=titles[view][0];$('page-description').textContent=titles[view][1];}
function badge(text,type=''){return `<span class="badge ${type}">${esc(text)}</span>`;}
function render(){if(!state)return;const ids=new Set(state.orders.map(o=>o.id));selected=new Set([...selected].filter(id=>ids.has(id)));$('connection-banner').classList.toggle('hidden',state.configured);$('connection-status').textContent=state.configured?'API 정보 저장됨':'연결 전';$('connection-status').classList.toggle('connected',state.configured);$('auto-toggle').checked=state.auto_enabled;$('auto-badge').textContent=!state.configured?'연결 대기':state.auto_enabled?'자동 수집 켜짐':'일시 정지';$('schedule-open').textContent=state.schedule_label+' ⌄';$('next-run').textContent=!state.configured?'API 연결 후 수집을 시작합니다.':state.auto_enabled?'다음 수집 '+dateText(state.next_run):'자동 수집이 꺼져 있습니다.';$('last-success').textContent=dateText(state.last_success);$('error-banner').classList.toggle('hidden',!state.last_error);$('error-banner').textContent=state.last_error;$('metric-all').innerHTML=`${state.orders.length.toLocaleString()} <small>건</small>`;$('metric-wait').innerHTML=`${state.orders.filter(o=>o.status==='PAYED'&&!o.claim).length.toLocaleString()} <small>건</small>`;$('metric-sent').innerHTML=`${state.orders.filter(o=>o.shipment?.state==='success').length.toLocaleString()} <small>건</small>`;$('metric-error').innerHTML=`${state.orders.filter(attention).length.toLocaleString()} <small>건</small>`;$('nav-count').textContent=state.orders.length;renderOrders();renderShipments();renderHistory();renderBusy();}
function renderOrders(){const rows=filtered(),pages=Math.max(1,Math.ceil(rows.length/30));page=Math.min(page,pages);const shown=rows.slice((page-1)*30,page*30);$('list-total').textContent=rows.length;$('page-number').textContent=`${page} / ${pages}`;$('prev-page').disabled=page===1;$('next-page').disabled=page===pages;$('order-body').innerHTML=shown.map(o=>`<tr><td class="check-cell"><input type="checkbox" data-select="${esc(o.id)}" aria-label="${esc(o.id)} 선택" ${selected.has(o.id)?'checked':''}></td><td><button class="id-button" data-detail="${esc(o.id)}">${esc(o.id)}</button><small>${esc(dateText(o.date))}</small></td><td><span class="product-name">${esc(o.name)}</span><small>${esc(o.option||'단일 상품')}</small></td><td>${esc(o.quantity)}</td><td>${esc(o.recipient)}</td><td>${badge(labels[o.status]||o.status,o.status==='PAYED'?'':'gray')}${o.claim?'<small>클레임 확인 필요</small>':''}</td><td>${o.shipment?badge(shippingLabels[o.shipment.state],['unknown','failed'].includes(o.shipment.state)?'error':''):badge('미등록','gray')}</td></tr>`).join('');$('orders-empty').classList.toggle('hidden',rows.length>0);if(!rows.length){$('orders-empty').querySelector('h3').textContent=state.orders.length?'검색 결과가 없습니다.':'처리할 주문을 한눈에';$('orders-empty').querySelector('p').innerHTML=state.orders.length?'검색어나 상태 필터를 바꿔 주세요.':state.configured?'지금 주문 수집을 눌러 첫 주문을 가져오세요.<br>첫 수집은 최근 24시간의 변경 주문을 가져옵니다.':'스마트스토어를 연결하고 첫 주문을 수집해 보세요.<br>수집한 주문은 이곳에서 선택하고 발주서로 내려받을 수 있어요.';$('empty-action').textContent=state.configured?'지금 주문 수집 →':'연결 설정 열기 →';$('empty-action').classList.toggle('hidden',state.orders.length>0);}$('select-all').checked=shown.length>0&&shown.every(o=>selected.has(o.id));$('select-all').indeterminate=shown.some(o=>selected.has(o.id))&&!$('select-all').checked;$('selected-card').textContent=selected.size;$('selection-text').textContent=`선택한 주문 ${selected.size}건`;['export-card','export-bottom'].forEach(id=>$(id).disabled=!selected.size);}
function renderShipments(){const rows=state.orders.filter(o=>o.shipment);$('shipments-empty').classList.toggle('hidden',rows.length>0);$('shipment-body').innerHTML=rows.map(o=>`<tr><td>${esc(o.id)}</td><td>${esc(state.carriers[o.shipment.carrier]||o.shipment.carrier)}<small>${esc(o.shipment.tracking)}</small></td><td>${badge(shippingLabels[o.shipment.state],['unknown','failed'].includes(o.shipment.state)?'error':o.shipment.state==='accepted'?'warning':'')}</td><td title="${esc(o.shipment.message)}">${esc(o.shipment.message)}<small>${esc(dateText(o.shipment.updated))}</small></td></tr>`).join('');}
function renderHistory(){$('history-empty').classList.toggle('hidden',state.events.length>0);$('history-list').innerHTML=state.events.map(e=>`<div class="history-row"><span class="history-symbol ${e.kind==='error'?'error':''}">${e.kind==='error'?'!':'✓'}</span><span>${esc(e.message)}</span><time>${esc(dateText(e.at))}</time></div>`).join('');}
function openSettings(){$('client-id').value='';$('client-secret').value='';$('account-id').value=state?.account_id||'';$('dispatch-enabled').checked=state?.dispatch_enabled||false;$('credentials-help').textContent=state?.configured?`저장된 ID 끝 4자리: ${state.client_id_hint} · 비워 두면 기존 키를 유지합니다.`:'저장된 키는 화면에 다시 표시하지 않습니다.';$('settings-error').textContent='';$('settings-dialog').showModal();}
async function collect(days){if(!state.configured){openSettings();return;}await action(async()=>{const result=await (await api('/api/collect',days?{days}:{})).json();toast(`주문 수집 완료 · 변경 ${result.updated}건 갱신`);});}
async function download(){await action(async()=>{const response=await api('/api/export',{ids:[...selected]});const url=URL.createObjectURL(await response.blob());const link=document.createElement('a');link.href=url;link.download=`발주서_${new Date().toISOString().slice(0,10)}.xlsx`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast(`${selected.size}건 발주서를 내려받았습니다.`);});}
async function upload(file){if(!file)return;if(!file.name.toLowerCase().endsWith('.xlsx'))return toast('.xlsx 파일을 선택해 주세요.',true);if(file.size>5*1024*1024)return toast('5MB 이하 파일을 선택해 주세요.',true);preview=null;$('preview-panel').classList.add('hidden');await action(async()=>{preview=await (await api('/api/invoices/preview',await file.arrayBuffer(),true)).json();$('preview-panel').classList.remove('hidden');$('file-name').textContent=file.name;$('preview-count').textContent=preview.rows.length+'건';$('preview-summary').textContent=`송신 가능 ${preview.valid}건 · 오류 ${preview.rows.length-preview.valid}건. 검토는 15분간 유효합니다.`;$('invoice-body').innerHTML=preview.rows.map(r=>`<tr><td>${r.row}</td><td>${esc(r.id)}</td><td>${esc(state.carriers[r.carrier]||r.carrier)}</td><td>${esc(r.tracking)}</td><td>${r.error?badge('확인 필요','error')+`<small>${esc(r.error)}</small>`:badge('송신 가능')}</td></tr>`).join('');$('send-note').textContent=state.dispatch_enabled?'오류 행은 제외하고 정상 행만 송신합니다.':'연결 설정에서 실제 송장 송신을 허용해야 합니다.';toast(`파일 검토 완료 · 송신 가능 ${preview.valid}건`);});}
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>showView(button.dataset.view)));
document.querySelectorAll('.close-dialog').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));
document.querySelectorAll('dialog').forEach(dialog=>dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();}}));
['settings-side','settings-top','connect-banner'].forEach(id=>$(id).addEventListener('click',openSettings));
$('empty-action').addEventListener('click',()=>state.configured?collect():openSettings());
$('collect-top').addEventListener('click',()=>collect());
$('reconcile').addEventListener('click',()=>collect());
$('invoice-go').addEventListener('click',()=>showView('invoices'));
['export-card','export-bottom'].forEach(id=>$(id).addEventListener('click',download));
$('search').addEventListener('input',()=>{page=1;renderOrders();});
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{filter=button.dataset.filter;page=1;document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b===button));renderOrders();}));
$('select-all').addEventListener('change',event=>{filtered().slice((page-1)*30,page*30).forEach(o=>event.target.checked?selected.add(o.id):selected.delete(o.id));renderOrders();});
$('order-body').addEventListener('change',event=>{const id=event.target.dataset.select;if(id){event.target.checked?selected.add(id):selected.delete(id);renderOrders();}});
$('order-body').addEventListener('click',event=>{const id=event.target.dataset.detail;if(!id)return;const o=state.orders.find(o=>o.id===id);const fields={'상품주문번호':o.id,'주문번호':o.order_id,'상품명':o.name,'옵션':o.option,'수량':o.quantity,'수취인':o.recipient,'연락처':o.phone,'우편번호':o.postcode,'주소':o.address,'배송메모':o.memo,'주문상태':labels[o.status]||o.status,'발주상태':o.place_status==='OK'?'발주 확인':o.place_status==='NOT_YET'?'발주 미확인':o.place_status,'클레임':o.claim||'없음'};$('order-detail').innerHTML=Object.entries(fields).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v||'—')}</dd>`).join('');$('detail-dialog').showModal();});
$('prev-page').addEventListener('click',()=>{page--;renderOrders();});$('next-page').addEventListener('click',()=>{page++;renderOrders();});
$('schedule-open').addEventListener('click',()=>{$('schedule-enabled').checked=state.auto_enabled;$('schedule-dialog').showModal();});
$('auto-toggle').addEventListener('change',event=>action(async()=>{await api('/api/schedule',{enabled:event.target.checked});toast('자동 수집 설정을 저장했습니다.');}));
$('schedule-form').addEventListener('submit',event=>{event.preventDefault();action(async()=>{await api('/api/schedule',{enabled:$('schedule-enabled').checked});$('schedule-dialog').close();toast('자동 수집 설정을 저장했습니다.');});});
$('settings-form').addEventListener('submit',event=>{event.preventDefault();action(async()=>{try{await api('/api/connection',{client_id:$('client-id').value,client_secret:$('client-secret').value,account_id:$('account-id').value,dispatch_enabled:$('dispatch-enabled').checked});$('client-id').value='';$('client-secret').value='';$('settings-dialog').close();toast('연결 정보를 저장했습니다. 연결 확인 또는 주문 수집을 실행해 주세요.');}catch(error){$('settings-error').textContent=error.message;throw error;}});});
$('connection-test').addEventListener('click',()=>action(async()=>{try{await api('/api/connection/test',{});$('settings-error').textContent='';toast('API 인증에 성공했습니다.');}catch(error){$('settings-error').textContent=error.message;throw error;}}));
$('recollect').addEventListener('click',()=>state.configured?$('recollect-dialog').showModal():openSettings());
$('recollect-form').addEventListener('submit',event=>{event.preventDefault();$('recollect-dialog').close();collect(Number($('lookback').value));});
$('invoice-file').addEventListener('change',event=>{upload(event.target.files[0]);event.target.value='';});
$('dropzone').addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();$('invoice-file').click();}});
['dragenter','dragover'].forEach(type=>$('dropzone').addEventListener(type,event=>{event.preventDefault();$('dropzone').classList.add('dragging');}));
['dragleave','drop'].forEach(type=>$('dropzone').addEventListener(type,event=>{event.preventDefault();$('dropzone').classList.remove('dragging');if(type==='drop')upload(event.dataTransfer.files[0]);}));
$('send-open').addEventListener('click',()=>{if(!preview?.valid)return;$('confirm-text').textContent=`검토한 정상 행 ${preview.valid}건을 스마트스토어에 송신합니다. 오류 행 ${preview.rows.length-preview.valid}건은 제외됩니다.`;$('send-dialog').showModal();});
$('send-confirm').addEventListener('click',()=>{const token=preview?.token;if(!token)return;$('send-dialog').close();action(async()=>{try{const result=await (await api('/api/invoices/send',{token,confirm:'EXECUTE'})).json();const rows=result.results.filter(Boolean);toast(`처리 완료 · 반영 확인 ${rows.filter(r=>r.state==='success').length}건 / 확인 대기·실패 ${rows.filter(r=>r.state!=='success').length}건`);}finally{preview=null;$('preview-panel').classList.add('hidden');}});});
$('today').textContent=new Date().toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'long',day:'numeric',weekday:'short'});
refresh().catch(error=>{toast('서버에 연결할 수 없습니다. 주문 관리 실행 파일을 다시 열어 주세요.',true);$('connection-status').textContent='서버 연결 끊김';});
setInterval(()=>refresh().catch(()=>{$('connection-status').textContent='서버 연결 끊김';}),5000);
